In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent.resolve()
PROC = PROJECT_ROOT / "data" / "processed"

df = pd.read_csv(PROC / "cleaned_apple_sales_enriched_realistic.csv")

In [3]:
df.head()

,sale_id,sale_date,store_id,product_id,quantity,product_name,launch_date,price,store_name,city,...,price_realistic,days_from_start,product_trend,trend_factor,store_factor,mu_demand,quantity_realistic,sales_amount_realistic,month,launch_year
0,RW-18212,2020-01-01,ST-41,P-73,2,Apple One,2020-01-01,199,Apple Central World,Bangkok,...,199.0,0,0.000783,1.0,1.219421,1.039677,3,597.0,1,2020
1,RX-6848,2020-01-01,ST-31,P-40,7,iPhone SE (3rd Generation),2020-01-01,429,Apple Shinjuku,Tokyo,...,429.0,0,0.000154,1.0,1.172288,10.813781,6,2574.0,1,2020
2,SV-39198,2020-01-01,ST-9,P-73,7,Apple One,2020-01-01,199,Apple Park Visitor Center,Cupertino,...,199.0,0,0.000783,1.0,0.958735,6.406862,5,995.0,1,2020
3,ZI-218670,2020-01-01,ST-20,P-70,1,Apple Fitness+,2020-01-01,79,Apple Kaerntner Strasse,Vienna,...,79.0,0,0.000692,1.0,1.109330,0.795094,1,79.0,1,2020
4,VB-48589,2020-01-01,ST-60,P-18,9,Beats Solo Pro,2020-01-01,299,Apple Antara,Mexico City,...,299.0,0,0.000495,1.0,1.203289,4.415985,4,1196.0,1,2020

In [4]:
print(df.columns)

Index(['sale_id', 'sale_date', 'store_id', 'product_id', 'quantity',
       'product_name', 'launch_date', 'price', 'store_name', 'city',
       'category_id', 'category_name', 'sales_amount', 'invalid_launch_flag',
       'product_age_days', 'exchange_rate', 'inflation_rate',
       'internet_usage_pct', 'country_norm_mapped', 'year', 'gdp_type',
       'gdp_per_capita', 'season_factor', 'economic_factor', 'promo_flag',
       'promo_factor', 'price_realistic', 'days_from_start', 'product_trend',
       'trend_factor', 'store_factor', 'mu_demand', 'quantity_realistic',
       'sales_amount_realistic', 'month', 'launch_year'],
      dtype='object')

In [5]:
df.shape

(1040200, 36)

In [6]:
unique_products = df["product_name"].unique()

print(unique_products)
print(len(unique_products))

['Apple One' 'iPhone SE (3rd Generation)' 'Apple Fitness+'
 'Beats Solo Pro' 'Beats Studio Buds' 'iPhone 14 Pro Max' 'iMac 24-inch'
 'Magic Trackpad' 'Apple Watch Nike Edition' 'MagSafe Battery Pack'
 'HomePod mini' 'AirTag' 'MacBook Air (Retina)' 'iPhone 12' 'iMac Pro'
 'Lightning to USB Cable' 'iPad Pro (M2)' 'MacBook Pro 13-inch'
 'Apple Watch Series 6' 'iPad Pro 12.9-inch' 'AirPods (3rd Generation)'
 'Apple Watch Series 9' 'Leather Case for iPhone'
 'Magic Keyboard with Touch ID' 'Apple Pencil (2nd Generation)'
 'MacBook Pro 14-inch' 'Smart Keyboard Folio' 'Mac Studio'
 'iPad (10th Generation)' 'Apple Watch Hermès' 'Apple News+'
 'Silicone Case for iPhone' 'Apple Music' 'Mac Pro (2023)'
 'Apple Watch Ultra' 'Magic Mouse' 'AirPods Pro' 'iPhone 14 Plus'
 'iMac 27-inch' 'Apple Watch Series 7' 'iPad Pro (M1)' 'Magic Keyboard'
 'iPhone 13 Pro' 'iPad Air (4th Generation)' 'MacBook Air (M2)'
 'AirPods Pro (2nd Generation)' 'MacBook Pro (Touch Bar)' 'iPhone 12 mini'
 'HomePod' 'AirPods Max' 'Apple Watch Series 8' 'iMac with Retina Display'
 'Mac Mini (M2)' 'iPhone 13' 'Beats Powerbeats Pro' 'iPhone 12 Pro Max'
 'Mac Pro (Rack)' 'HomePod (2nd Generation)' 'iPad mini (6th Generation)'
 'Mac Mini' 'Smart Cover for iPad' 'MacBook Pro 16-inch'
 'AirPods (2nd Generation)' 'iCloud' 'Apple TV HD' 'Beats Fit Pro'
 'Apple TV (3rd Generation)' 'MacBook Air (M1)'
 'iPad Air (5th Generation)' 'MacBook' 'MacBook (Retina)'
 'iPhone 13 Pro Max' 'iPad Pro 11-inch' 'Apple TV+' 'MacBook (Early 2015)'
 'Apple Arcade' 'iPhone 12 Pro' 'MagSafe Charger' 'Apple Watch SE'
 'iPhone 13 mini' 'Apple Pencil (1st Generation)' 'Apple Watch Series 5'
 'Apple TV 4K' 'iPhone 14 Pro' 'iPad (9th Generation)'
 'iPad mini (5th Generation)' 'Mac Pro (Tower)' 'iPhone 14']
88

In [7]:
# لو الداتا الأصلية فيها الأعمدة product_name و launch_date
df[["product_name", "launch_date"]].drop_duplicates().sort_values("launch_date")

                     product_name launch_date
0                       Apple One  2020-01-01
107                        iCloud  2020-01-01
106      AirPods (2nd Generation)  2020-01-01
105           MacBook Pro 16-inch  2020-01-01
102          Smart Cover for iPad  2020-01-01
...                           ...         ...
995966          Apple Watch Ultra  2024-08-30
1004177              Apple Arcade  2024-09-13
1017778               AirPods Pro  2024-10-06
1018391         iPhone 14 Pro Max  2024-10-07
1034987                 Apple TV+  2024-11-04

[177 rows x 2 columns]

In [8]:
pd.set_option("display.max_rows", None)

product_launches = (
    df[["product_name", "launch_date"]]
    .drop_duplicates()
    .sort_values("launch_date")
)

print(product_launches)

                          product_name launch_date
0                            Apple One  2020-01-01
107                             iCloud  2020-01-01
106           AirPods (2nd Generation)  2020-01-01
105                MacBook Pro 16-inch  2020-01-01
102               Smart Cover for iPad  2020-01-01
95                            Mac Mini  2020-01-01
89          iPad mini (6th Generation)  2020-01-01
88            HomePod (2nd Generation)  2020-01-01
86                      Mac Pro (Rack)  2020-01-01
109                        Apple TV HD  2020-01-01
85                   iPhone 12 Pro Max  2020-01-01
83                           iPhone 13  2020-01-01
78                       Mac Mini (M2)  2020-01-01
77            iMac with Retina Display  2020-01-01
74                Apple Watch Series 8  2020-01-01
73                         AirPods Max  2020-01-01
70                             HomePod  2020-01-01
69                      iPhone 12 mini  2020-01-01
67             MacBook Pro (Touch Bar)  2020-01-01
84                Beats Powerbeats Pro  2020-01-01
64        AirPods Pro (2nd Generation)  2020-01-01
110                      Beats Fit Pro  2020-01-01
118                   MacBook Air (M1)  2020-01-01
268         iPad mini (5th Generation)  2020-01-01
248              iPad (9th Generation)  2020-01-01
239                      iPhone 14 Pro  2020-01-01
226                        Apple TV 4K  2020-01-01
214               Apple Watch Series 5  2020-01-01
201      Apple Pencil (1st Generation)  2020-01-01
200                     iPhone 13 mini  2020-01-01
198                     Apple Watch SE  2020-01-01
112          Apple TV (3rd Generation)  2020-01-01
188                    MagSafe Charger  2020-01-01
157                       Apple Arcade  2020-01-01
153               MacBook (Early 2015)  2020-01-01
144                          Apple TV+  2020-01-01
140                   iPad Pro 11-inch  2020-01-01
139                  iPhone 13 Pro Max  2020-01-01
138                   MacBook (Retina)  2020-01-01
127                            MacBook  2020-01-01
122          iPad Air (5th Generation)  2020-01-01
178                      iPhone 12 Pro  2020-01-01
62                    MacBook Air (M2)  2020-01-01
61           iPad Air (4th Generation)  2020-01-01
60                       iPhone 13 Pro  2020-01-01
21                Apple Watch Series 6  2020-01-01
20                 MacBook Pro 13-inch  2020-01-01
19                       iPad Pro (M2)  2020-01-01
18              Lightning to USB Cable  2020-01-01
16                            iMac Pro  2020-01-01
15                           iPhone 12  2020-01-01
14                MacBook Air (Retina)  2020-01-01
12                              AirTag  2020-01-01
22                  iPad Pro 12.9-inch  2020-01-01
11                        HomePod mini  2020-01-01
9             Apple Watch Nike Edition  2020-01-01
8                       Magic Trackpad  2020-01-01
7                         iMac 24-inch  2020-01-01
6                    iPhone 14 Pro Max  2020-01-01
5                    Beats Studio Buds  2020-01-01
4                       Beats Solo Pro  2020-01-01
3                       Apple Fitness+  2020-01-01
1           iPhone SE (3rd Generation)  2020-01-01
10                MagSafe Battery Pack  2020-01-01
23            AirPods (3rd Generation)  2020-01-01
24                Apple Watch Series 9  2020-01-01
26             Leather Case for iPhone  2020-01-01
59                      Magic Keyboard  2020-01-01
53                       iPad Pro (M1)  2020-01-01
52                Apple Watch Series 7  2020-01-01
49                        iMac 27-inch  2020-01-01
48                      iPhone 14 Plus  2020-01-01
47                         AirPods Pro  2020-01-01
46                         Magic Mouse  2020-01-01
45                   Apple Watch Ultra  2020-01-01
44                      Mac Pro (2023)  2020-01-01
43                         Apple Music  2020-01-01
41            Silicone Case for iPhone  2020-01-01
40                         Apple News+  2020-01-01
38                  Apple Watch Hermès  2020-01-01
37              iPad (10th Generation)  2020-01-01
36                          Mac Studio  2020-01-01
33                Smart Keyboard Folio  2020-01-01
32                 MacBook Pro 14-inch  2020-01-01
29       Apple Pencil (2nd Generation)  2020-01-01
27        Magic Keyboard with Touch ID  2020-01-01
272                    Mac Pro (Tower)  2020-01-01
555                          iPhone 14  2020-01-01
640                       HomePod mini  2020-01-02
6990              Apple Watch Series 7  2020-01-13
8680              MacBook Air (Retina)  2020-01-16
11008                   Apple Watch SE  2020-01-20
37337                        iPhone 12  2020-03-05
39976             Smart Keyboard Folio  2020-03-10
50004             MagSafe Battery Pack  2020-03-27
71359                        Apple One  2020-05-02
76454                           AirTag  2020-05-11
79381                   Magic Keyboard  2020-05-16
84067                 MacBook Air (M2)  2020-05-24
102331        Apple Watch Nike Edition  2020-06-24
106434       Apple TV (3rd Generation)  2020-07-01
119864        iMac with Retina Display  2020-07-24
130480                         HomePod  2020-08-11
147521               iPhone 12 Pro Max  2020-09-09
149301            Apple Watch Series 9  2020-09-12
150496                   iPad Pro (M1)  2020-09-14
157392                     Apple Music  2020-09-26
158082                        Mac Mini  2020-09-27
168653        HomePod (2nd Generation)  2020-10-15
177800                  iPhone 12 mini  2020-10-31
204308            Beats Powerbeats Pro  2020-12-15
223354             MacBook Pro 13-inch  2021-01-17
228549                          iCloud  2021-01-26
230396    AirPods Pro (2nd Generation)  2021-01-29
251356       iPad Air (5th Generation)  2021-03-06
260813                   iPhone 13 Pro  2021-03-22
270281                    iMac 24-inch  2021-04-07
280388       iPad Air (4th Generation)  2021-04-24
287488                  Apple Fitness+  2021-05-06
294391          iPad (10th Generation)  2021-05-18
301487        AirPods (3rd Generation)  2021-05-30
309667                       iPhone 14  2021-06-13
313743                  iPhone 13 mini  2021-06-20
349464                        iMac Pro  2021-08-20
352333                   iPad Pro (M2)  2021-08-25
390504                   Mac Mini (M2)  2021-10-30
405057                     Apple TV HD  2021-11-24
422421                   iPhone 14 Pro  2021-12-24
424842             MacBook Pro 16-inch  2021-12-28
439623        Silicone Case for iPhone  2022-01-22
441968                     Apple News+  2022-01-26
466481           iPad (9th Generation)  2022-03-08
483002                    HomePod mini  2022-04-05
507436                    iMac 27-inch  2022-05-17
519403                  Mac Pro (Rack)  2022-06-06
523418        AirPods (2nd Generation)  2022-06-13
529296         Leather Case for iPhone  2022-06-23
540177            Apple Watch Series 8  2022-07-12
562450                     AirPods Max  2022-08-19
604831                 Mac Pro (Tower)  2022-10-31
610769      iPhone SE (3rd Generation)  2022-11-10
615986            MacBook (Early 2015)  2022-11-19
620624      iPad mini (6th Generation)  2022-11-27
636118                   Beats Fit Pro  2022-12-23
646619      iPad mini (5th Generation)  2023-01-10
655155            Smart Cover for iPad  2023-01-25
668595                     Apple TV 4K  2023-02-17
698513    Magic Keyboard with Touch ID  2023-04-09
709067            Apple Watch Series 6  2023-04-27
714757                iPad Pro 11-inch  2023-05-07
737625                       iPhone 13  2023-06-15
740969   Apple Pencil (2nd Generation)  2023-06-21
741653                    HomePod mini  2023-06-22
754876                  Mac Pro (2023)  2023-07-14
779619                     Magic Mouse  2023-08-26
784842                  iPhone 14 Plus  2023-09-04
792369                         MacBook  2023-09-17
809980                MacBook (Retina)  2023-10-17
824256            Apple Watch Series 5  2023-11-10
824313              iPad Pro 12.9-inch  2023-11-10
825059                MacBook Air (M1)  2023-11-11
857192          Lightning to USB Cable  2024-01-05
881268                      Mac Studio  2024-02-15
887662                  Beats Solo Pro  2024-02-26
905786                 MagSafe Charger  2024-03-27
929579               Beats Studio Buds  2024-05-07
930410               iPhone 13 Pro Max  2024-05-09
932171             MacBook Pro 14-inch  2024-05-12
939604                  Magic Trackpad  2024-05-25
952873         MacBook Pro (Touch Bar)  2024-06-17
960349   Apple Pencil (1st Generation)  2024-06-30
980108                   iPhone 12 Pro  2024-08-03
995966               Apple Watch Ultra  2024-08-30
1004177                   Apple Arcade  2024-09-13
1017778                    AirPods Pro  2024-10-06
1018391              iPhone 14 Pro Max  2024-10-07
1034987                      Apple TV+  2024-11-04

In [9]:
# Group by category and count the number of UNIQUE product names
unique_products_per_category = df.groupby('category_name')['product_name'].nunique().reset_index()

# Rename the columns for clarity
unique_products_per_category.columns = ['category_name', 'total_unique_products']

# Sort from highest number of products to lowest
unique_products_per_category = unique_products_per_category.sort_values(by='total_unique_products', ascending=False)

display(unique_products_per_category)

          category_name  total_unique_products
0           Accessories                     14
5            Smartphone                     13
1                 Audio                     11
2               Desktop                     10
3                Laptop                     10
8                Tablet                     10
9              Wearable                      9
7  Subscription Service                      7
6      Streaming Device                      3
4         Smart Speaker                      2

In [10]:
# Group by both year and category, then count the UNIQUE product names sold
unique_products_per_year_cat = df.groupby(['year', 'category_name'])['product_name'].nunique().reset_index()

# Rename the columns for clarity
unique_products_per_year_cat.columns = ['year', 'category_name', 'total_unique_products']

# Create a pivot table to make it easy to read (Categories on the left, Years across the top)
pivot_unique = unique_products_per_year_cat.pivot(index='category_name', columns='year', values='total_unique_products')

# Fill any missing data with 0 and convert to integers
pivot_unique = pivot_unique.fillna(0).astype(int)

display(pivot_unique)

year                  2020  2021  2022  2023  2024
category_name
Accessories             14    14    14    14    14
Audio                   11    11    11    11    11
Desktop                 10    10    10    10    10
Laptop                  10    10    10    10    10
Smart Speaker            2     2     2     2     2
Smartphone              13    13    13    13    13
Streaming Device         3     3     3     3     3
Subscription Service     7     7     7     7     7
Tablet                  10    10    10    10    10
Wearable                 9     9     9     9     9

In [11]:
# Group by both the Launch Year and category, then count the UNIQUE product names
unique_products_per_launch = df.groupby(['launch_year', 'category_name'])['product_name'].nunique().reset_index()

# Rename the columns for clarity
unique_products_per_launch.columns = ['launch_year', 'category_name', 'total_unique_products']

# Create a pivot table (Categories on the left, Launch Years across the top)
pivot_launch = unique_products_per_launch.pivot(index='category_name', columns='launch_year', values='total_unique_products')

# Fill any missing data with 0 and convert to integers
pivot_launch = pivot_launch.fillna(0).astype(int)

display(pivot_launch)

launch_year           2020  2021  2022  2023  2024
category_name
Accessories             14     0     2     4     4
Audio                   11     2     4     0     3
Desktop                 10     3     3     1     1
Laptop                  10     2     1     3     2
Smart Speaker            2     0     0     1     0
Smartphone              13     4     1     2     3
Streaming Device         3     1     0     1     0
Subscription Service     7     2     1     0     2
Tablet                  10     4     2     3     0
Wearable                 9     0     1     2     1